configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin since it *excludes* files.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

dependencies {
    implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    api "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
    // Remove the next line if you don't want to depend on the API
    // modApi "dev.architectury:architectury-fabric:${rootProject.architectury_version}"

    common(project(path: ":common")) { transitive false }
    shadowCommon(project(path: ":common")) { transitive false }
    common(project(path: ":core", configuration: "shadow")) { transitive false }
    shadowCommon(project(path: ":core", configuration: "shadow"))
}

processResources {
    dependsOn(":core:shadowJar")

    from(zipTree(project(":core").tasks.named("shadowJar").flatMap { it.archiveFile })) {
        include "assets/**"
        include "META-INF/**"
    }

    inputs.property "version", project.version
    inputs.property "loaderVersion", rootProject.fabric_loader_version
    inputs.property "mcVersion", rootProject.minecraft_version

    filesMatching("fabric.mod.json") {
        expand(
                version: project.version,
                loaderVersion: rootProject.fabric_loader_version,
                mcVersion: rootProject.minecraft_version
        )
    }
}

shadowJar {
    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
}

sourcesJar {
    def commonSources = project(":common").tasks.named("sourcesJar")
    def coreSources = project(":core").tasks.named("sourcesJar")

    dependsOn commonSources
    dependsOn coreSources

    from commonSources.flatMap { it.archiveFile }.map { zipTree(it) }
    from coreSources.flatMap { it.archiveFile }.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publishing {
    publications {
        mavenFabric(MavenPublication) {
            artifactId = rootProject.archives_base_name + "-" + project.name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
    }
}
