plugins {
    id "com.gradleup.shadow" version "9.4.1"
    id "net.fabricmc.fabric-loom" version "1.16-SNAPSHOT" apply false
}

def platforms = rootProject.enabled_platforms.split(",").toList()
platforms.add("common")

subprojects {

    repositories {
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }

    if (platforms.contains(project.name) && project.name != "neoforge") {
        apply plugin: "net.fabricmc.fabric-loom"

        repositories {
            maven { url "https://maven.neoforged.net/releases/" }
        }

        dependencies {
            minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
        }
    }
}

allprojects {
    apply plugin: "java"
    apply plugin: "maven-publish"
    apply plugin: "com.gradleup.shadow"

    base {
        archivesName = rootProject.archives_base_name
    }

    version = rootProject.mod_version
    group = rootProject.maven_group

    repositories {
        // Add repositories to retrieve artifacts from in here.
        // You should only use this when depending on other mods because
        // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
        // See https://docs.gradle.org/current/userguide/declaring_repositories.html
        // for more information about repositories.
    }

    tasks.withType(JavaCompile) {
        options.encoding = "UTF-8"
        options.release = 25
    }

    java {
        toolchain.languageVersion.set(JavaLanguageVersion.of(25))
        withSourcesJar()
    }
}

build {
    dependsOn("buildAll")
}

tasks.register("buildAll", Copy) {
    group = "build"
    description = "Build shadow jars and collect outputs"

    def mcVersion = rootProject.minecraft_version
    def modVersion = rootProject.mod_version

    def libOut = file("$rootDir/build/libs")
    into(libOut)

    def tasksToCollect = [
            ["fabric",   "Concerto-mc${mcVersion}-fabric-${modVersion}.jar"],
            ["neoforge", "Concerto-mc${mcVersion}-neoforge-${modVersion}.jar"],
            ["paper",    "Concerto-mc${mcVersion}-paper-${modVersion}.jar"]
    ]

    tasksToCollect.each { entry ->
        def (modName, targetName) = entry

        def shadowTask = project(":${modName}").tasks.named("shadowJar")

        dependsOn(shadowTask)

        from(shadowTask) {
            rename { fileName -> targetName }
        }
    }
}