java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
    sourceCompatibility = JavaVersion.VERSION_16
    targetCompatibility = JavaVersion.VERSION_16
}

apply plugin: "com.gradleup.shadow"

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencies {
    implementation 'com.google.code.gson:gson:2.11.0'
    implementation "org.jetbrains:annotations:24.1.0"

    bundled 'com.google.zxing:core:3.3.0'

    bundled('com.googlecode.soundlibs:mp3spi:1.9.5.4') {
        exclude group: 'com.googlecode.soundlibs', module: 'tritonus-share'
        exclude group: 'junit', module: 'junit'
    }

    bundled 'com.github.GregTaoo:JustFLAC:1.0.0'

    bundled 'com.github.trilarion:vorbis-support:1.1.0'

    bundled('com.googlecode.soundlibs:tritonus-all:0.3.7.2') {
        exclude group: 'com.googlecode.soundlibs', module: 'tritonus-share'
    }

    bundled 'net.jthink:jaudiotagger:3.0.1'
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 16
}
