repositories {
    maven { url "https://repo.papermc.io/repository/maven-public/" }
}

configurations {
    my.canBeResolved(true)
    implementation.extendsFrom(my)
}

def paperVersion = "${rootProject.minecraft_version}-R0.1-SNAPSHOT"

dependencies {
    compileOnly("io.papermc.paper:paper-api:${paperVersion}")

    my(project(path: ":core", configuration: "shadow")) { transitive = false }
}

// Bukkit only accepts patch-level api-version strings from 1.20.5 onward
def bukkitApiVersion = rootProject.minecraft_version.tokenize(".")[0..1].join(".")

processResources {
    inputs.property "version", project.version
    inputs.property "apiVersion", bukkitApiVersion

    filesMatching("plugin.yml") {
        expand(
                version: project.version,
                apiVersion: bukkitApiVersion
        )
    }
}

jar {
    enabled = false
    dependsOn(shadowJar)
}

shadowJar {
    configurations = [project.configurations.my]
    archiveClassifier = null
    exclude("top/gregtao/concerto/libs/**")
}
