repositories {
    maven { url "https://repo.papermc.io/repository/maven-public/" }
}

configurations {
    my.canBeResolved(true)
    implementation.extendsFrom(my)
}

def paperVersion = "${rootProject.minecraft_version}.build.+"

dependencies {
    compileOnly("io.papermc.paper:paper-api:${paperVersion}")

    my(project(path: ":core", configuration: "shadow")) { transitive = false }
}

processResources {
    inputs.property "version", project.version
    inputs.property "apiVersion", rootProject.minecraft_version

    filesMatching("plugin.yml") {
        expand(
                version: project.version,
                apiVersion: rootProject.minecraft_version
        )
    }
}

jar {
    enabled = false
    dependsOn(shadowJar)
}

shadowJar {
    configurations = [project.configurations.my]
    archiveClassifier = null
    exclude("top/gregtao/concerto/libs/**")
}
