name: Concerto
version: '${version}'
main: top.gregtao.concerto.paper.ConcertoPaperPlugin
description: Concerto
author: [ GregTao ]
website: https://github.com/gregtaoo/concerto
api-version: '${apiVersion}'

channels:
  - concerto:main

permissions:
  concerto.room.create:
    description: Allow player to create music rooms
    default: op
